apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        labels.io/utility: development
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        env:
          - name: VERSION
            value: "pre-release"
        portj:
        - containerPort: 80
